# Monolith OS — makepkg Configuration
# /etc/makepkg.conf

DLAGENTS=('file::/usr/bin/curl -qgC - -o %o %u'
          'ftp::/usr/bin/curl -qfC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u'
          'http::/usr/bin/curl -qb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'https::/usr/bin/curl -qb "" -fLC - --retry 3 --retry-delay 3 -o %o %u')

CFLAGS="-march=native -O3 -pipe -fstack-protector-strong"
CXXFLAGS="${CFLAGS}"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
RUSTFLAGS="-C opt-level=3 -C target-cpu=native"
MAKEFLAGS="-j$(nproc)"
DEBUG_CFLAGS="-g"
DEBUG_CXXFLAGS="-g"

BUILDENV=(!distcc color !ccache check !sign)
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)

INTEGRITY_CHECK=(sha256)
STRIP_BINARIES="--strip-all"
STRIP_SHARED="--strip-unneeded"
STRIP_STATIC="--strip-debug"

PKGEXT='.pkg.tar.zst'
SRCEXT='.src.tar.gz'
COMPRESSZST=(zstd -c -T0 --ultra -20 -)
