# Monolith OS — pacman Configuration
# /etc/pacman.conf

[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
VerbosePkgLists
ParallelDownloads = 10
ILoveCandy
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# Monolith custom repository
[monolith]
SigLevel = Optional TrustAll
Server = https://repo.monolith-os.org/$arch

# Official Arch repositories
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
